#12 Add 2 players + add quarters delimitation
marmelab/pentago-symfony pull request #4
Opened 2021-02-01 18:07 UTC by Clebiez

#12 I want to switch players

- [x] Add in the gameService the currentPlayer field
- [x] When rotating a quarter, switching to the other player (your turn is finished)
- [x] When adding a marble, now adding in the board the value of the player (1 or 2) 
- [x] Add some basic CSS to detect more easily quarters (borders variations)

2021-02-01 19:40 UTC, zyhou commented on public/css/main.css
> +  font-family: "Arial";
comic sans ms 
![image](https://user-images.githubusercontent.com/2212144/106509253-ab4dad80-64cd-11eb-9e93-6faa2d43b93f.png)

2021-02-01 19:43 UTC, zyhou requested changes

2021-02-01 19:43 UTC, zyhou commented on src/Service/BoardService.php
> +        $board[$position[0]][$position[1]] = $value;
I didn't see this before, can you clone/copy the array ? Immutability is powerful tools

2021-02-01 19:43 UTC, zyhou commented on templates/game/index.html.twig
> +		{% if turnStatus == constant('App\\Service\\GameService::ADD_MARBLE_STATUS') %}
+1

2021-02-01 20:49 UTC, fzaninotto commented
I think you can improve the UI a bit:

- when the buttons appear, the grid moves down. It's disturbing
- why ask the user to click on buttons representing the quadrants rather than the quadrants themselves?

2021-02-02 08:21 UTC, zyhou approved these changes

2021-02-02 08:29 UTC, merged